server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/tripsense_user
    username: ${DB_USER:postgres}
    password: ${DB_PASS:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  access-token-expiration-ms: 900000 # 15 minutes
  refresh-token-cookie-name: refreshToken
  idle-timeout-days: 7
  absolute-timeout-days: 30
  cookie-secure: false

email-service:
  url: ${EMAIL_SERVICE_URL:http://localhost:8082}
