services:
  db:
    image: postgres:17-alpine
    container_name: user-postgres
    environment:
      POSTGRES_DB: tripsense_user
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-123456}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  discovery-server:
    build:
      context: .
      dockerfile: services/discovery-server/Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    container_name: api-gateway
    environment:
      EUREKA_DEFAULT_ZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
    ports:
      - "8080:8080"
    restart: unless-stopped

  place-service:
    build:
      context: .
      dockerfile: services/place-service/Dockerfile
    container_name: place-service
    environment:
      EUREKA_DEFAULT_ZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
    ports:
      - "8083:8082"
    restart: unless-stopped

  mail-service:
    build:
      context: .
      dockerfile: services/mail-service/Dockerfile
    container_name: mail-service
    ports:
      - "8082:8082"
    env_file:
      - ./env/.env
    environment:
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_REGISTER=true
      - EUREKA_FETCH=true
    restart: unless-stopped

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    container_name: user-service
    env_file:
      - ./env/.env
    environment:
      - DB_HOST=db
      - EMAIL_SERVICE_URL=http://mail-service:8082
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_REGISTER=true
      - EUREKA_FETCH=true
    depends_on:
      - db
      - mail-service
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  postgres_data: