package fu.tripsense.recommendation.domain;

public enum RecommendationReasonCode {
  STRONG_RETRIEVAL_MATCH,
  STRONG_SEMANTIC_MATCH,
  MATCHES_USER_PREFERENCE,
  HIGH_CONFIDENCE_RATING,
  VERIFIED_QUIETNESS,
  NEAR_TRIP_AREA,
  MATCHES_TRIP_CONTEXT,
  POPULAR_CHOICE,
  PREVIOUSLY_SAVED
}
