server {
    listen 80;
    server_name _;

    location /health {
        proxy_pass http://api-gateway:8080/health;
    }

    location /api/auth/ {
        proxy_pass http://user-service:8081/api/auth/;
    }

    location /api/places/ {
        proxy_pass http://api-gateway:8080/api/places/;
    }
}
