server {
    listen 80;
    server_name tripsense.duckdns.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /health {
        default_type application/json;
        return 200 '{"status":"BOOTSTRAPPING"}';
    }

    location / {
        default_type text/plain;
        return 200 "Tripsense SSL Bootstrapping in progress...\n";
    }
}
