services:
  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: tripsense_user
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  discovery-server:
    image: ${IMAGE_REGISTRY}/${IMAGE_OWNER}/${IMAGE_PROJECT}-discovery-server:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"

  email-service:
    image: ${IMAGE_REGISTRY}/${IMAGE_OWNER}/${IMAGE_PROJECT}-email-service:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      RESEND_API_KEY: ${RESEND_API_KEY}

  place-service:
    image: ${IMAGE_REGISTRY}/${IMAGE_OWNER}/${IMAGE_PROJECT}-place-service:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      EUREKA_DEFAULT_ZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server

  user-service:
    image: ${IMAGE_REGISTRY}/${IMAGE_OWNER}/${IMAGE_PROJECT}-user-service:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      EMAIL_SERVICE_URL: http://email-service:8082
    depends_on:
      - db
      - email-service

  api-gateway:
    image: ${IMAGE_REGISTRY}/${IMAGE_OWNER}/${IMAGE_PROJECT}-api-gateway:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      EUREKA_DEFAULT_ZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - user-service
      - place-service

volumes:
  postgres_data: