"use client";

import * as React from "react";
import {
  Route,
  Search,
  Calendar,
  MapPin,
  Sparkles,
  Users,
  Globe,
  Lock,
  Share2,
  MoreVertical,
  Archive,
  ExternalLink,
} from "lucide-react";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

interface TripRecord {
  id: string;
  title: string;
  destination: string;
  creator: string;
  creatorEmail: string;
  dates: string;
  durationDays: number;
  placesCount: number;
  visibility: "PUBLIC" | "PRIVATE" | "SHARED";
  isAiGenerated: boolean;
  status: "ACTIVE" | "ARCHIVED";
}

const initialTrips: TripRecord[] = [
  {
    id: "trip-1",
    title: "5-Day Tokyo Culinary & Temple Expedition",
    destination: "Tokyo, Japan",
    creator: "Alex Traveler",
    creatorEmail: "alex.traveler@mindtrip.ai",
    dates: "Oct 12 - Oct 17, 2026",
    durationDays: 5,
    placesCount: 16,
    visibility: "PUBLIC",
    isAiGenerated: true,
    status: "ACTIVE",
  },
  {
    id: "trip-2",
    title: "Da Nang Coastal Relaxation & Ba Na Hills",
    destination: "Da Nang, Vietnam",
    creator: "Gia Bao",
    creatorEmail: "giabaoworking362004@gmail.com",
    dates: "Nov 01 - Nov 04, 2026",
    durationDays: 4,
    placesCount: 9,
    visibility: "SHARED",
    isAiGenerated: true,
    status: "ACTIVE",
  },
  {
    id: "trip-3",
    title: "Weekend in Paris - Art & Cafés",
    destination: "Paris, France",
    creator: "Sarah Miller",
    creatorEmail: "sarah.m@gmail.com",
    dates: "Dec 05 - Dec 08, 2026",
    durationDays: 3,
    placesCount: 11,
    visibility: "PUBLIC",
    isAiGenerated: false,
    status: "ACTIVE",
  },
  {
    id: "trip-4",
    title: "Private Family Retreat Hoi An",
    destination: "Hoi An, Vietnam",
    creator: "John Do",
    creatorEmail: "john.do@traveler.com",
    dates: "Jan 10 - Jan 14, 2027",
    durationDays: 5,
    placesCount: 7,
    visibility: "PRIVATE",
    isAiGenerated: true,
    status: "ACTIVE",
  },
];

export default function AdminTripsPage() {
  const [trips, setTrips] = React.useState<TripRecord[]>(initialTrips);
  const [searchQuery, setSearchQuery] = React.useState("");
  const [visibilityFilter, setVisibilityFilter] = React.useState<string>("ALL");

  const filteredTrips = trips.filter((t) => {
    const matchSearch =
      t.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      t.destination.toLowerCase().includes(searchQuery.toLowerCase()) ||
      t.creator.toLowerCase().includes(searchQuery.toLowerCase());
    const matchVis = visibilityFilter === "ALL" || t.visibility === visibilityFilter;
    return matchSearch && matchVis;
  });

  const toggleArchive = (id: string) => {
    setTrips((prev) =>
      prev.map((t) =>
        t.id === id
          ? { ...t, status: t.status === "ACTIVE" ? "ARCHIVED" : "ACTIVE" }
          : t,
      ),
    );
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-card border border-border p-6 rounded-2xl shadow-2xs">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Badge variant="outline" className="bg-primary/10 text-primary border-primary/20 text-xs">
              <Route className="h-3.5 w-3.5 mr-1" /> Trip Oversight
            </Badge>
            <span className="text-xs text-muted-foreground">Trip Service Catalog</span>
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-foreground">Trips & Itineraries</h1>
          <p className="text-sm text-muted-foreground">
            Monitor itineraries created by travelers and generated by the AI Planner.
          </p>
        </div>

        <Badge className="bg-primary text-primary-foreground font-mono text-xs px-3 py-1 self-start sm:self-auto">
          {trips.length} Active Itineraries
        </Badge>
      </div>

      {/* Filters */}
      <div className="flex flex-col sm:flex-row gap-3 items-stretch sm:items-center justify-between bg-card border border-border p-4 rounded-xl shadow-2xs">
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground pointer-events-none" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search by title, destination, or creator..."
            className="w-full rounded-lg border border-border bg-background py-1.5 pl-9 pr-4 text-xs text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all"
          />
        </div>

        <div className="flex items-center gap-1 bg-muted p-1 rounded-lg text-xs">
          <span className="text-muted-foreground px-2 font-medium">Visibility:</span>
          {["ALL", "PUBLIC", "SHARED", "PRIVATE"].map((vis) => (
            <button
              key={vis}
              onClick={() => setVisibilityFilter(vis)}
              className={`px-3 py-1 rounded-md font-medium transition-all ${
                visibilityFilter === vis
                  ? "bg-background text-foreground shadow-2xs font-semibold"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              {vis}
            </button>
          ))}
        </div>
      </div>

      {/* Table */}
      <Card className="bg-card border-border shadow-2xs overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-muted/50 border-b border-border text-muted-foreground uppercase text-micro tracking-wider font-semibold">
              <tr>
                <th className="p-4">Trip Title & Destination</th>
                <th className="p-4">Creator</th>
                <th className="p-4">Timeline</th>
                <th className="p-4">Places</th>
                <th className="p-4">Engine</th>
                <th className="p-4">Visibility</th>
                <th className="p-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {filteredTrips.map((trip) => (
                <tr key={trip.id} className="hover:bg-muted/30 transition-colors">
                  <td className="p-4">
                    <div className="font-semibold text-foreground text-sm">{trip.title}</div>
                    <div className="text-muted-foreground flex items-center gap-1 mt-0.5">
                      <MapPin className="h-3 w-3 text-primary" /> {trip.destination}
                    </div>
                  </td>

                  <td className="p-4">
                    <div className="font-medium text-foreground">{trip.creator}</div>
                    <div className="text-micro text-muted-foreground">{trip.creatorEmail}</div>
                  </td>

                  <td className="p-4">
                    <div className="text-foreground font-mono">{trip.dates}</div>
                    <div className="text-micro text-muted-foreground">{trip.durationDays} Days planned</div>
                  </td>

                  <td className="p-4 font-mono font-medium text-foreground">
                    {trip.placesCount} spots
                  </td>

                  <td className="p-4">
                    {trip.isAiGenerated ? (
                      <Badge className="bg-primary/10 text-primary border-primary/20 flex items-center gap-1 w-fit text-micro">
                        <Sparkles className="h-3 w-3" /> AI Crafted
                      </Badge>
                    ) : (
                      <Badge variant="outline" className="text-micro text-muted-foreground">
                        Manual
                      </Badge>
                    )}
                  </td>

                  <td className="p-4">
                    <Badge
                      variant="outline"
                      className={`text-micro flex items-center gap-1 w-fit ${
                        trip.visibility === "PUBLIC"
                          ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20"
                          : trip.visibility === "SHARED"
                          ? "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20"
                          : "bg-muted text-muted-foreground"
                      }`}
                    >
                      {trip.visibility === "PUBLIC" && <Globe className="h-3 w-3" />}
                      {trip.visibility === "SHARED" && <Share2 className="h-3 w-3" />}
                      {trip.visibility === "PRIVATE" && <Lock className="h-3 w-3" />}
                      <span>{trip.visibility}</span>
                    </Badge>
                  </td>

                  <td className="p-4 text-right">
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="ghost" size="icon" className="h-8 w-8 rounded-lg">
                          <MoreVertical className="h-4 w-4" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end" className="w-44 text-xs">
                        <DropdownMenuItem
                          onClick={() => toggleArchive(trip.id)}
                          className="cursor-pointer"
                        >
                          <Archive className="h-4 w-4 mr-2" />
                          <span>{trip.status === "ACTIVE" ? "Archive Trip" : "Restore Trip"}</span>
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}
